### ISSUE TITLE
Reset Game Function not working

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/game-project#349] opened 2016-11-03 16:29 UTC
I have a reset button and when it is clicked, it resets the game board. It resets everything visually and clears out the text from the gameboard array. However, it does not reset the player turn.

Here is the reset game function
```
const clickhandlers = require('./clickhandlers');

let game_reset = function(){
  clickhanders.player_switch = 'x';
  clickhandlers.board = ['', '', '', '', '', '', '', '', ''];
  $('.content').text('');
  $('.content').css('background-color', 'white');

};
```

And here is the player switch function and variable it corresponds to.

```
let player_switch = 'x';

let player_turn = function(){
  if(player_switch==='x'){
    player_switch = 'y';
  }
  else{
    player_switch = 'x';
  }
};
```

I also console.logged for after the reset function runs and it does log that player_switch is x so, here I am

**Comment by raq929** [comment] 2016-11-03 16:32
I'm not quite understanding the problem. It sounds like it is resetting the player to x. (Maybe the last part of what you typed was cut off?)

**Comment by neugierige** [comment] 2016-11-03 16:32
I echo Rachel's confusion. What is your intended behavior? If the 1st player is always player X, isn't that what reset means?

**Comment by akradin** [comment] 2016-11-03 16:42
The problem is everything seems to be lining up, the reset function should set player_switch to X and based off of everytyhing I am seeing that _does_ happen. 

However, if you end a game on X turn and hit reset, O will start the next game.

**Comment by neugierige** [comment] 2016-11-03 16:49
If you are successfully setting the value of `clickhanders.player_switch` to `x` when `game_reset` is called, and there is no mechanism for changing the `player_switch` other than `player_turn`, then my guess is that `player_turn` is somehow getting called when you do the reset. Check your code for all the places where `player_turn` is called.

**Comment by akradin** [comment] 2016-11-03 17:22
`player_turn` is only being called in the function that manipulates the gameboard which is this

``` js
let change_box= function(){

  if($(this).text()===''){
    if(player_switch==='x'){
      $(this).css('background-color','black');
      $(this).text('X');
      player_turn();
    }
    else{
      $(this).css('background-color','blue');
      $(this).text('Y');
      player_turn();
    }

  }
  check_game();
  console.log(board);

  logic.check_win(board);
};
```

**Comment by neugierige** [comment] 2016-11-03 17:33
where are you right now?

**Comment by RealWeeks** [comment] 2016-11-03 18:32
[INSERT WEEKS FLEX GIF HERE]

@akradin can you write up the solution and close the issue

**Comment by akradin** [comment] 2016-11-03 19:27
Issue resolved by making reset function not modular and having it in the same file as check game board function

**Closed as completed** 2016-11-03 19:29 UTC
