### ISSUE TITLE
passing data to signup

### ISSUE THREAD

**Issue by pvdri** [ga-wdi-boston/game-project#102] opened 2016-04-06 20:31 UTC
I'm confused as to how to pass data in the sign up...

``` js
const signUp = (success, failure, data) => {
  event.preventDefault();
  $.ajax({
    method: 'POST',
    url: 'http://localhost:3000/sign-up',
    data: {

    }
  }).done(success)
  .fail(failure);
};
```

**Comment by RealWeeks** [comment] 2016-04-06 20:36
You did pass data to the signup function on the first line `const signUp = (success, failure, data) => {` looks like you didn't put any data in your ajax request however.

**Comment by RealWeeks** [comment] 2016-04-06 20:37
Also look closely, where are you sending you data to?

**Comment by pvdri** [comment] 2016-04-06 20:43
it listed sign up under the API documentation - that's where I'm sending it to

**Comment by RealWeeks** [comment] 2016-04-06 21:36
that's the endpoint, what's the full address?

**Comment by RealWeeks** [comment] 2016-04-06 23:15
@pvdri has this issue been resolved? It sounds like it is from the other issue you have open.  If it is please close, if not please ask more questions.

**Comment by laurenfazah** [comment] 2016-04-07 13:20
@pvdri this issue looks like a duplicate of your other. Please close this one if you no longer need it or follow up with a question regarding this that is different from your other open issue. Thank you.

**Comment by RealWeeks** [comment] 2016-04-07 14:10
Similar to #118 #107

**Comment by laurenfazah** [comment] 2016-04-07 15:08
@

**Closed as completed by laurenfazah** 2016-04-07 15:08 UTC
