### ISSUE TITLE
Help with constructor functions

### ISSUE THREAD

**Issue by Soboscott** [ga-wdi-boston/game-project#422] opened 2017-01-26 14:20 UTC
I have psudo code for having the players to create an array so that I can match it against winning combinations but I am not sure how to write the constructor.
I have looked at the constructor repo and have combed the internet to help me with the syntax.
can you please help me.

function to make an array
const playerOne = function playerOne(){

let result = [];
for (let i=0; i,4; i++){
result[i] = playerOne[i];
}
};

**Comment by bernardlee** [comment] 2017-01-26 14:32
Constructor functions in JavaScript are typically written in this form.

```javascript
const SomeConstructor = function SomeConstructor(someParameter) {
  this.someParameter = someParameter;
}

const myNewObject = new SomeConstructor('something here');
```

**Comment by Soboscott** [comment] 2017-01-26 15:01
would it look something like this?

const gameBoard = [0,1,2,3,4,5,6,7,8,];
const playerOne = function playerOne(gameBoard){
this.gameBoard = gameBoard;
};
const new gameBoard = new playerOne [];  **<= I don't think this is right but don't know how to express it**

const playerTwo = function playerTwo(gameBoard){
this.gameBoard = gameBoard;
};
const new gameBoard = new playerTwo [];  **<= I don't think this is right but don't know how to express it**

**Comment by bernardlee** [comment] 2017-01-26 15:24
You cannot call `const new variableName = ...` it needs to be `const variableName =  new ConstructorFunction(...arguments);`.

As it is written right now, it looks like you're trying to create two constructor functions, playerOne and playerTwo.  By convention, constructor functions should be capitalized.

**Comment by Soboscott** [comment] 2017-01-26 15:55
Thank you for replying, I'm still trying to get my head around this concept.

I am trying to make two constructors, one for each player, my thinking is that this will create and store the "picks" each player will make so that I can compare them with the winning combos.

I think this also requires a for loop to get the additional "picks".

I'm looking for guidance to see if I am on the right track.

**Comment by bernardlee** [comment] 2017-01-26 16:13
Work on the simplest thing first and then add on to it.  Instead of worrying about how the players will take turns and how to check for victory conditions, write some simple functions to manipulate a game state (e.g., an array).  For example, if your game state were represented by a 9-element array, write a function that can manipulate it by changing a specified element (array index) into a player's token, represented by a string.

**Comment by samordonez** [comment] 2017-01-26 16:14
If you are using a constructor function, you would probably be best off creating a single generic Player constructor and then defining two new Players.

```javascript
function Player (args) {
  //define attributes of object
}

const playerOne = new Player(arguments);
const playerTwo = new Player(otherArguments);
```

**Comment by jrhorn424** [comment] 2017-01-26 16:50
> I'm looking for guidance to see if I am on the right track.

I agree with @bernardlee, @Soboscott. You're not far off track at all. I think you are focusing on the wrong thing. The board array (or whatever you choose, I like array for this) is the "right" place to store these picks, not the player objects.

Can you try writing your checkWin function in such a way that it utilizes the board?

If constructors are making your head spin, would it be ok to use object literals instead, then go back to constructors if you have time?

**Comment by Soboscott** [comment] 2017-01-26 17:12
this is what I have as far as winning functions:

```js
// edited by @jrhorn424 - please format and preview next time
const Game = function (board) {
  this.board = board;
  this.currentPlayer = 'x';
  this.wins = [
        [0,1,2],[3,4,5],[6,7,8], // Row
        [0,3,6],[1,4,7],[2,5,8], // col
        [0,4,8],[2,4,6]]; // diag
};
```

**Comment by jrhorn424** [comment] 2017-01-26 17:25
I see. So you're statically defining a list of win conditions. Nice!

How would you use those conditions in a function, along with the board, in order to check for a winner? This function, whatever you name it, should be probably become a property on `Game.prototype`.

**Comment by Soboscott** [comment] 2017-01-26 18:56
I think that would look like:
let possibleWins = function () {
  if ((board[0] === 'x' && board[1] === 'x' && board[2] === 'x') ||
      (board[3] === 'x' && board[4] === 'x' && board[5] === 'x') ||
thru all permeations then
    {alert("X wins!");
}  else if (same as above) y wins
else draw.
now I will work on making the prototype

**Comment by jrhorn424** [comment] 2017-01-26 19:47
You're on track!

**Comment by MicFin** [comment] 2017-01-27 14:13
@Soboscott did this work? Please update us on how the issue is going or close it with your solution if it is solved

**Closed as completed** 2017-01-27 19:52 UTC
