### ISSUE TITLE
Modal error on page load, but still appears to be working

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/game-project#509] opened 2017-04-05 17:53 UTC
I created a modal for my Sign Up. With each page load, the modal is producing an error, but I am still able to sign up a new user.  

The file the error references contains only game logic that isn't being used yet. Not sure how to resolve this.

![image](https://cloud.githubusercontent.com/assets/25553014/24719253/1460fba8-1a07-11e7-9847-e808909bb0f6.png)

**Comment by danman01** [comment] 2017-04-05 18:00
Do you know which file and / or line of code is responsible for causing this error? And, do you have a pretty good idea of the cause of the error by reading the error message?

**Comment by payne-chris-r** [comment] 2017-04-05 18:13
Also `modal !== module` 😜

**Comment by danielleletarte** [comment] 2017-04-05 18:20
Ugh...modals on the brain! Sorry for the confusion, it would help if I could read 😜. The error seems to be resolved now. I had changed the name of this file to something else which may have been root cause. I changed it back and all is well.

**Comment by payne-chris-r** [comment] 2017-04-05 18:23
Yep! Exactly. The `spec/example.spec` is actually a test that requires certain things out of the `example.js` file. If you want to change the name (or delete `example.js`), you would also need to modify (or delete) the `spec/example.spec` file.

**Comment by payne-chris-r** [comment] 2017-04-05 18:24
If you've resolved the issue, please close it. Thanks!

**Closed as completed** 2017-04-05 18:26 UTC
