### ISSUE TITLE
Boostrap side effect

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#437] opened 2017-01-26 20:36 UTC
My bootstrap html  code works and can be seen, however the styling does not show up, and has effected some of the scss styling.

I have linked the stylesheet in the <head> as such:
```
<link rel="stylesheet" type="text/css" href="assets/styles/index.scss">
```
and have also tried:
```
<link rel="stylesheet" type="text/scss" href="assets/styles/index.scss">
```

It was fine last night and haven't touched it so I am confused as to why it would change. I have not moved files around either. 
What other factors  could affect this?

**Comment by BenGitsCode** [comment] 2017-01-26 20:37
Did you read the comment in the `index.html` HEAD, that specifically instructs you not to do that?

**Comment by doremaxime** [comment] 2017-01-26 20:47
hmmm... i thought it said we could add to it.

**Comment by jrhorn424** [comment] 2017-01-26 20:49
> hmmm... i thought it said we could add to it.

No. We've already installed bootstrap for you. It's been working since you downloaded the template.

If it's not rendering correctly, it's because there's an error in your JS somewhere. That can make the styling break due to the way we've wired things together.

`grunt nag`, console errors, ...

**Comment by doremaxime** [comment] 2017-01-26 20:50
thank you

**Comment by jrhorn424** [comment] 2017-01-26 20:58
> grunt nag, console errors, ...

I was asking for input.

Please don't close issues without a resolution.

Was it a JS error after all? Did you remove your link tag from the head of index.html?

**Comment by doremaxime** [comment] 2017-01-26 21:01
Sorry I thought you were telling me to run those.
I have not done anything as I am trying to get the engine running.
I was stuck on the engine so i spent a couple minutes with display and found that issue that I could not resolve.

**Comment by jrhorn424** [comment] 2017-01-26 21:03
I understand.

If you're working on something and it isn't complete, it is normal for it to break the display of the app.

**Comment by jrhorn424** [comment] 2017-01-26 21:04
> Sorry I thought you were telling me to run those.

I was, and I wanted to see the output as a response.

Let's leave this open until you get a resolution, thanks.

**Comment by MicFin** [comment] 2017-01-27 14:10
@doremaxime did this work? Please update use on how the issue is going or close it after commenting how you found a solution.

**Comment by doremaxime** [comment] 2017-01-27 14:35
i have not worked on this yet, i am working on my game engine. i was told not to close this until i get a solution.

**Comment by doremaxime** [comment] 2017-01-28 01:00
when there are no issues in javascript the display of the css/bootstrap works. it is properly shown now.

**Closed as completed** 2017-01-28 01:51 UTC
