### ISSUE TITLE
Not able to access API

### ISSUE THREAD

**Issue by eliottenos** [ga-wdi-boston/game-project#596] opened 2017-04-12 13:15 UTC
Terminal returns following when trying to access server...

$ bundle exec rails server
=> Booting Puma
=> Rails 4.2.7.1 application starting in development on http://localhost:4741
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[17918] Puma starting in cluster mode...
[17918] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[17918] * Min threads: 8, max threads: 32
[17918] * Environment: development
[17918] * Process workers: 4
[17918] * Preloading application
[17918] * Listening on tcp://localhost:4741
Exiting
/Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE)
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `new'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `add_tcp_listener'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:260:in `block in add_tcp_listener'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:259:in `each'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:259:in `add_tcp_listener'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:102:in `block in parse'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `each'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `parse'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:133:in `load_and_bind'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:370:in `run'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/rack/handler/puma.rb:51:in `run'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/server.rb:80:in `start'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/eliottenos/wdi/projects/game-project-api/bin/rails:9:in `require'
	from /Users/eliottenos/wdi/projects/game-project-api/bin/rails:9:in `<top (required)>'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client/command.rb:7:in `call'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/client.rb:30:in `run'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/bin/spring:49:in `<top (required)>'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `load'
	from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-1.7.2/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/eliottenos/wdi/projects/game-project-api/bin/spring:13:in `require'
	from /Users/eliottenos/wdi/projects/game-project-api/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by Jcornmanhomonoff** [comment] 2017-04-12 13:42
In what directory/repo are you running this command?

**Comment by eliottenos** [comment] 2017-04-12 13:44
game-project-api

**Comment by BenGitsCode** [comment] 2017-04-12 13:45
The problem is hidden in that error message right at the top.

Why are you running a rails server?

**Comment by eliottenos** [comment] 2017-04-12 13:50
ahh ok, seems to be running now as must have not control c'd out of it correctly last night.

for the api authentication - is that correct?

**Comment by BenGitsCode** [comment] 2017-04-12 13:53
To test your authentication? Sure that's fine, serving your own version of the game api is a great way to test the auth (you can see the rails logs).

**Comment by BenGitsCode** [comment] 2017-04-12 13:59
I think you can close this issue, but I just want to clarify what happened in the OP just so you know in the future. 

`initialize': Address already in use - bind(2) for "::1" port 4741 (Errno::EADDRINUSE) from /Users/eliottenos/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:innew'`

That line of your error message has everything you need to know. Please close this issue with the resolution. Let me know if it's still unclear.

**Comment by eliottenos** [comment] 2017-04-12 14:01
Thanks, the server was already running in some capacity due to not exiting correctly.

Shut down terminal and computer to be sure and is now up and running

**Closed as completed** 2017-04-12 14:01 UTC

**Comment by BenGitsCode** [comment] 2017-04-12 14:03
Specifically, it was never shut down at all, so that port was already running a server. Good job!  👍 Please remember to close the issue.
